Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:Password123!@tcp(127.0.0.1:3306)/location?parseTime=True&loc=Local"
  DatabaseName: "location"
  Username: "root"
  Password: "Password123!"

NewRelicSettings:
  LicenseKey: "YOUR_LICENSE_KEY"
  AppName: "YOUR_APP_NAME"

JwtSettings:
  SecretKey: "MY_SECRET_KEY"